### ISSUE TITLE
Consumption on raven?

### ISSUE THREAD

**Issue by andersalavik** [adriankumpf/teslamate#191]
I wont get any consumption? 
Anything else seams to work grate.

We have an Model X Raven.

<img width="805" alt="bild" src="https://user-images.githubusercontent.com/50051433/66201287-4e58a200-e6a3-11e9-968d-f63ac9dac76d.png">

**Comment by adriankumpf** [comment]
To estimate the consumption TM ships with a set of efficiency factors (Wh/km) for different vehicles. Those factors have been crowdsourced and are not not complete ... yet! 

You can contribute the factor for your Model X after charging a couple of times: on the efficiency dashboard it displays the derived efficiency factors based on your data. If a value has been confirmed several times, feel free to post a screenshot of those values!

**Comment by mapchen** [comment]
I experience the same issue with a raven. 

For me its written Model X in the web page and the vehicle seems to be identified. At least i can not see a problem in the log.

**Comment by adriankumpf** [comment]
Then what's mentioned above applies to you too. If both of you can confirm the same efficiency factor it makes sense to add it.

> For me its written Model X in the web page and the vehicle seems to be identified. At least i can not see a problem in the log.

It won't log an error. It's just debug information to identify new vehicles and it should be written right after starting the TeslaMate.

**Comment by mapchen** [comment]
Lets see if this helps regarding the identification error: 
teslamate_1  | waiting for postgres at db:5432 (2sec)
teslamate_1  | 08:15:07.133 [info] Already up
teslamate_1  | 08:15:35.544 [info] Running TeslaMateWeb.Endpoint with cowboy 2.6.3 at :::4000 (http)
teslamate_1  | 08:15:35.550 [info] Access TeslaMateWeb.Endpoint at http://192.168.0.31
teslamate_1  | 08:15:35.823 [info] Adding elevation to 1000 positions ...
teslamate_1  | 08:15:35.875 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:37.173 [info] Found 'TeslaMatthias'
teslamate_1  | 08:15:37.249 [info] Initializing handler
teslamate_1  | 08:15:37.250 [info] Connection has been established
teslamate_1  | 08:15:38.954 car_id=1 [info] Start / :online
teslamate_1  | 08:15:38.956 [warn] Vehicle could not be identified!
teslamate_1  |
teslamate_1  | %TeslaApi.Vehicle.State.VehicleConfig{
teslamate_1  |   can_accept_navigation_requests: true,
teslamate_1  |   can_actuate_trunks: true,
teslamate_1  |   car_special_type: "base",
teslamate_1  |   car_type: "modelx",
teslamate_1  |   charge_port_type: "EU",
teslamate_1  |   eu_vehicle: true,
teslamate_1  |   exterior_color: "Pearl",
teslamate_1  |   has_air_suspension: true,
teslamate_1  |   has_ludicrous_mode: false,
teslamate_1  |   key_version: nil,
teslamate_1  |   motorized_charge_port: true,
teslamate_1  |   perf_config: nil,
teslamate_1  |   plg: true,
teslamate_1  |   rear_seat_heaters: 3,
teslamate_1  |   rear_seat_type: 4,
teslamate_1  |   rhd: false,
teslamate_1  |   roof_color: "None",
teslamate_1  |   seat_type: 0,
teslamate_1  |   spoiler_type: "Passive",
teslamate_1  |   sun_roof_installed: 0,
teslamate_1  |   third_row_seats: "None",
teslamate_1  |   timestamp: 1570601738528,
teslamate_1  |   trim_badging: nil,
teslamate_1  |   wheel_type: "AeroTurbine20"
teslamate_1  | }
teslamate_1  | 08:15:39.707 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:39.835 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:40.370 [info] GET /
teslamate_1  | 08:15:40.470 [info] Sent 200 in 100ms
teslamate_1  | 08:15:41.129 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:43.322 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:46.643 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:47.611 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:48.426 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:51.616 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:52.628 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:53.652 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:55.656 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:56.516 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:57.443 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:15:58.659 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:01.096 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:01.642 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:02.667 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:03.674 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:05.662 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:07.664 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:08.668 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:09.681 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:10.690 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:11.891 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:11.954 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:13.664 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:14.673 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:15.673 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:18.142 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:18.400 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:18.700 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:20.687 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:22.205 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:24.718 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:27.723 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:28.676 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:29.712 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:30.722 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:32.101 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:32.305 [info] Adding elevation to 334 positions ...
teslamate_1  | 08:16:32.487 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:32.553 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:35.721 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:36.733 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:37.733 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:39.712 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:40.733 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:43.721 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:16:44.729 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 08:35:23.577 [error] Mounting lv:phx-oZC0XS-7 failed while verifying session with: :invalid
teslamate_1  | 08:35:24.638 [error] Mounting lv:phx-oZC0XS-7 failed while verifying session with: :invalid
teslamate_1  | 08:35:26.720 [error] Mounting lv:phx-oZC0XS-7 failed while verifying session with: :invalid
teslamate_1  | 08:35:31.595 [info] GET /
teslamate_1  | 08:35:31.611 [info] Sent 200 in 15ms
teslamate_1  | 08:35:51.999 car_id=1 [info] Suspending logging
teslamate_1  | 09:05:55.149 car_id=1 [info] Suspending logging

---------------------------------

regarding the effeciency factors. I have not charged a lot so maybe this page populates correctly after a while ?

![image](https://user-images.githubusercontent.com/56200461/66460064-787cdc00-ea76-11e9-94d6-663fabcfba81.png)

**Comment by adriankumpf** [comment]
Yes, this definitely helps. However, it will be difficult to distinguish between LR and Performance.

> regarding the effeciency factors. I have not charged a lot so maybe this page populates correctly after a while ?

That's exactly how it is. It needs multiple charges that took longer than 15 minutes.

I'm wondering, though, why you're getting an error. Could you hover over the red icon and paste the message that's being displayed here?

**Comment by mapchen** [comment]
> I'm wondering, though, why you're getting an error. Could you hover over the red icon and paste the message that's being displayed here?

It says:
pq: division by zero

**Comment by adriankumpf** [comment]
> > I'm wondering, though, why you're getting an error. Could you hover over the red icon and paste the message that's being displayed here?
> 
> It says:
> pq: division by zero

That's fixed with the latest release (v1.11).

**Comment by andersalavik** [comment]
I think my optioncodes ar fucked up. 
 

19:49:19.969 [warn] Vehicle could not be identified!

%TeslaApi.Vehicle.State.VehicleConfig{
  can_accept_navigation_requests: true,
  can_actuate_trunks: true,
  car_special_type: "base",
  car_type: "modelx",
  charge_port_type: "EU",
  eu_vehicle: true,
  exterior_color: "Pearl",
  has_air_suspension: true,
  has_ludicrous_mode: false,
  key_version: nil,
  motorized_charge_port: true,
  perf_config: nil,
  plg: true,
  rear_seat_heaters: 3,
  rear_seat_type: 3,
  rhd: false,
  roof_color: "None",
  seat_type: 0,
  spoiler_type: "Passive",
  sun_roof_installed: 0,
  third_row_seats: "FuturisFoldFlat",
  timestamp: 1570902559768,
  trim_badging: nil,
  wheel_type: "AeroTurbine20"
}

option codes: ["AD15", "MDL3", "PBSB", "RENA", "BT37", "ID3W", "RF3G", "S3PB", "DRLH", "DV2W",
 "W39B", "APF0", "COUS", "BC3B", "CH07", "PC30", "FC3P", "FG31", "GLFR", "HL31",
 "HM31", "IL31", "LTPB", "MR31", "FM3B", "RS3H", "SA3P", "STCP", "SC04", "SU3C",
 "T3CA", "TW00", "TM00", "UT3P", "WR00", "AU3P", "APH3", "AF00", "ZCST", "MI00",
 "CDM0"]


<img width="943" alt="bild" src="https://user-images.githubusercontent.com/50051433/66705644-a2a9f480-ed29-11e9-86e1-edaf53ce9e55.png">

**Comment by adriankumpf** [comment]
I guess Tesla still haven't fixed this issue in their back end. That makes it pretty much impossible to automatically distinguish between the Model X LR and Performance unless both have the same hard-coded factor.

**Comment by adriankumpf** [comment]
Fixed with abfa8c96d5ef1d6007f356afd6f84aea5c1f2bdc

**Comment by mapchen** [comment]
I am still struggling to get anything to be populated into the derived efficiency table.
![image](https://user-images.githubusercontent.com/56200461/67491180-c7309580-f674-11e9-83fd-4a1fc941620e.png)
Any other hint what to do?

**Comment by adriankumpf** [comment]
The fix is not yet released :)

**Comment by mapchen** [comment]
just to give some feedback. This is how it looks after v1.12 upgrade. I do get now efficiency factors but average consumption is still not shown. @adriankumpf I can not say if this is by intention?

![image](https://user-images.githubusercontent.com/56200461/67758573-3b38b800-fa3e-11e9-881b-b27c4f2f6e00.png)

**Comment by adriankumpf** [comment]
Which type of range do you have configured – rated or ideal?

**Comment by mapchen** [comment]
rated.

**Comment by adriankumpf** [comment]
Ah, I almost forgot – the consumption values will update the next time you charge. To trigger a recalculation immediately, temporarily change the preferred range.
