### ISSUE TITLE
Safari browser crashes under the unit settings menu

### ISSUE THREAD

**Issue by petrovic3** [adriankumpf/teslamate#261]
**Describe the bug**

Safari browser crashes if you try to select a different unit under the unit settings dropdown menu.

**To Reproduce**

Try to pick a different unit other than km under the settings on the port 4000 portal under the settings section.
I am only able to reproduce this on Safari. It works fine on chrome or firefox.

**Relevant entries from the logs**
Nothing specifically interesting in the logs.Just a couple 200 GET requests:
Nov 18 19:19:48 ip-172-31-10-127 docker-compose[18403]: teslamate_1  | 19:19:48.521 [info] GET /settings
Nov 18 19:19:48 ip-172-31-10-127 docker-compose[18403]: teslamate_1  | 19:19:48.523 [info] Sent 200 in 2ms
Nov 18 19:20:48 ip-172-31-10-127 docker-compose[18403]: teslamate_1  | 19:20:48.699 [info] GET /settings
Nov 18 19:20:48 ip-172-31-10-127 docker-compose[18403]: teslamate_1  | 19:20:48.701 [info] Sent 200 in 2ms

**Screenshots**
![Screenshot 2019-11-18 at 13 20 39](https://user-images.githubusercontent.com/7103420/69082960-d3efa180-0a06-11ea-90f6-37b71e768630.png)

**Operating environment (please complete the following information):**

OS: MacOS Mojave 10.14.6 (18G95)
Version: v1.12.2

**Comment by adriankumpf** [comment]
I could not reproduce this behavior with Safari 13.0.3 on macOS Catalina. I assume that the problem was caused by a dependency. Chances are that this is already fixed on the master branch.

**Comment by adriankumpf** [comment]
Does the issue still exist with version v1.13.0?

**Comment by jpirnie** [comment]
Happened to me as well with Mojave v10.14.6.

**Comment by petrovic3** [comment]
> Does the issue still exist with version v1.13.0?

Yes, this is still happening with v.1.13.1. It makes the whole browser crash

**Comment by krezac** [comment]
I wasn't even able to get to it. Safari Version 13.0.3 (14608.3.10.10.1).
 
There is "spinner" overlay (on both main page and settings) and the dropdown can't be expanded. I see
```
WebSocket connection to 'wss://xxx.yyy.net/live/websocket?baseUrl=https%3A%2F%2Fxxx.yyy.net&referrer=https%3A%2F%2Fxxx.yyy.net%2F&vsn=2.0.0' failed: Unexpected response code: 401
```
in console. In Chrome it works just fine (on the same machine). The server is using traefik in pretty much default config (as in the advanced doc). Ports 80 and 443 forwarded on firewall.

**Comment by adriankumpf** [comment]
I still cannot reproduce this. Since it works in all other browsers, I assume that there is a bug in Safari. Please report back if you find out more or if a future update of Safari fixes the problem.
